---
exp_name: avg
exp_dir: ./exp
seed: 4
num: 0 # # of augmentation
gpu: cuda:0

model: ProbGraphUnet
encoder: avg
in_channels: 4
hidden_channels: [32,64,128,256]
pool_ratios: [0.5,0.5,0.5,0.5]
out_channels: 32
latent_channels: 6
num_samples: 16
num_classes: 14
sum_res: False

